USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS MOVIELENS;
CREATE SCHEMA IF NOT EXISTS MOVIELENS.RAW;

CREATE SCHEMA IF NOT EXISTS MOVIELENS.STAGING;
CREATE SCHEMA IF NOT EXISTS MOVIELENS.DIM;
CREATE SCHEMA IF NOT EXISTS MOVIELENS.FCT;
